#%RAML 1.0 Library

usage: Defines various generally useful RAML elements related to HTTP itself.

types:
  #
  StatusCode:
    description: HTTP response status code.
    type: integer
    minimum: 100
    maximum: 599
    examples:
      ok: 200
      not-found: 404
      internal-server-error: 500
  #
  DefaultRespBody:
    description: |
      A default response body, which is used because the current HTTP response does not suggest a more specific body.
      This response body re-iterates the HTTP response status code and explains why that status code was returned.
    type: object
    properties: 
      code:
        description: The status code of this HTTP response.
        type: StatusCode
      message:
        description: |
          An explanation of why the given response status code was returned.
          Note that this is not the standard human-readable alternative to the status code (i.e. it is not "Not Found" for a `404` response). Instead, this is a concrete explanation for this specific response.
        type: string
    examples:
      ok:
        code: 200
        message: The request to delete a FooBar was successfully processed
      not-found:
        code: 404
        message: The FooBar with the given ID does not exit